import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar';
import Header from '@/components/header';
import MobileHeader from '@/components/ui/mobile-header';

export const metadata: Metadata = {
  title: 'BookVault',
  description: 'Generated by create next app',
};

const interfont = Inter({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={interfont.className}>{children}</body>
    </html>
  );
}
